name: Mobile Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  mobile_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.19.x', '1.23.x']

    steps:
      - uses: actions/checkout@v4
########################################################################################################################

      - name: Cache [ubuntu] init
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            go.sum
            go.sum
          key: ${{ runner.os }}-${{ matrix.go-version }}-local
          restore-keys: ${{ runner.os }}-${{ matrix.go-version }}-

      - name: Cache [macos] init
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
            go.sum
            go.sum
          key: ${{ runner.os }}-${{ matrix.go-version }}-local
          restore-keys: ${{ runner.os }}-${{ matrix.go-version }}-
          enableCrossOsArchive: true

      - name: Cache [windows] init
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\go-build
            ~\go\pkg\mod
            go.sum
            go.sum
          key: ${{ runner.os }}-${{ matrix.go-version }}-local
          restore-keys: ${{ runner.os }}-${{ matrix.go-version }}-
          enableCrossOsArchive: true

########################################################################################################################

      - name: Goland init
        uses: WillAbides/setup-${{ matrix.go-version }}-faster@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: go.sum [macos, ubuntu] init
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
        run: |
          if [ ! -f "go.sum" ]; then
            go mod tidy
          fi
        working-directory: ${{ github.workspace }}

      - name: go.sum [windows] init
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          if (-not (Test-Path "go.sum")) {
            go mod tidy
          }
        working-directory: ${{ github.workspace }}

########################################################################################################################

      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install gcc libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

      - name: Tests
        run: go test -test.benchtime 10ms -tags "ci mobile" ./...